# DocGuard Configuration
source: ./llms.txt

journeys:
  getting_started:
    - How do I install this?
    - How do I get started?
    - Where are examples?

  development:
    - How do I run tests?
    - How do I debug issues?
    - Where can I get help?

# AI Provider (openai or anthropic)
provider: openai
model: gpt-4o-mini
# Optional: Set API key here instead of environment variable
# api_key: sk-...
