# DocGuard Configuration
# Define what questions your documentation must answer

questions:
  # Critical questions - these will fail the check if not answerable
  critical:
    - How do I install this project?
    - How do I get started?
    - Where can I find examples?

  # Important questions - these will warn if not answerable
  important:
    - How do I configure this?
    - How do I report issues?
    - What are the system requirements?

  # Nice to have - these are informational only
  nice_to_have:
    - How do I contribute?
    - Where is the changelog?

# OpenAI API configuration
# You can set this here or use OPENAI_API_KEY environment variable
# api_key: sk-...

# Model to use (gpt-4o-mini is recommended for cost)
model: gpt-4o-mini
# Where to look for documentation (optional, defaults to current directory)
# docs_path: ./docs
